### ISSUE TITLE
Roadmap for getting the modpack out there (and more)

### ISSUE THREAD

**Issue by copygirl** [copygirl/obsidian-Modpack#32]
We're currently lacking players, and therefore also reason to continue working on the pack. While I think the modpack should become even more social and multiplayer oriented, our server definitely doesn't have the players it needs. If we can't get this fixed, things are better off when the development of the pack is dropped.
- [ ] Write up a document about the (long term) goals of the pack.
- [ ] "Advertise" the pack and get people to try it.
- [ ] "Advertise" the server and get people to join it.
- [ ] Collect feedback and suggestions.
- [ ] @copygirl: Get back into modding.
- [ ] Get in touch with mod developers.
- [ ] Suggest feature additions that would improve the pack.
- [ ] Suggest working together on new mods or bigger features.

What does everyone think about this?

**Comment by gigabit101** [comment]
Hey copy I'm not sure what to say about this but don't get down about this to much not everyone likes to play minecraft the same way. I enjoy playing the pack but iv only played single player as I didn't know the server was open. Also as for getting back into modding you should only do it if you enjoy it like I still do. I know some time if feels pointless as some users have no respect for the developer but in other cases they love it so much they are willing to tell you what a great job you are doing or donate just some things to think about

**Comment by Voxel-Friend** [comment]
copy-Senpai can do the thing!

**Comment by copygirl** [comment]
Wrote up a [modpack mission wiki page](https://github.com/copygirl/obsidian-Modpack/wiki/Modpack-Mission) for now, it shall have to do.

**edit:** I messaged the [/r/feedthebeast](http://www.reddit.com/r/feedthebeast/) moderators about being able to post a submission on their subreddit, even though it would probably break their "no server advertisement" rule, waiting for a reply.

Anyone know and other good places we could find interested players?

**Comment by copygirl** [comment]
Turns out that indeed, /r/feedthebeast did not allow an exception for my submission.

**Comment by BarbasTheDog** [comment]
/r/FeedTheBeastservers is their place for advertising servers, but you probably already knew that.

Another idea is to ship the server's IP with the pack or to have a custom main menu with a link to where people can apply and then simply advertise the pack.

Advertising packs is not only allowed in /r/feedthebeast, it's also encouraged.

**EDIT:** I, myself, will apply once I get back home from a trip I'm about to go in now that I know you want more people on the server. :D
